### ISSUE TITLE
did you ever finish this?

### ISSUE THREAD

**Issue by mvanholsteijn** [soulwing/oaq-adapter#1]
Hi @ceharris,
We are trying to use your AQ resource adapter, and found that it refers to createConnectionConsumer() on the AQ connection object. Unfortunately, this is not implemented in Oracle AQ.

did you ever finish this? 

Cheers,

Mark

**Comment by ceharris** [comment]
Hey there! The project for which this is dependency made a decision to abandon Oracle AQ and this project was never finished. I did have some uncommitted work-in-progress that I went ahead and pushed today. I no longer have access to the Oracle JDBC driver and AQ API dependencies so I can't build it.

I also updated the README to better reflect this project's status.

**Comment by mvanholsteijn** [comment]
thank you! I will keep you posted.

**Comment by ceharris** [comment]
I found one other note from a colleague regarding an OAQ resource adapter. He'd been looking at the [Generic JMS RA](https://github.com/jms-ra/generic-jms-ra) project and had concluded that it might be a better starting point for creating a OAQ resource adapter that could be deployed in Wildfly/JBossAS. Just something to consider.
